// Mock data for the MediaFlow platform demo

export const mockVendors = [
  {
    id: '1',
    name: 'Rajesh Kumar',
    email: 'rajesh@freshbites.com',
    phone: '+91 98765 43210',
    businessName: 'Fresh Bites Restaurant',
    businessCategory: 'Food & Beverage',
    city: 'Mumbai',
    role: 'vendor',
    password: 'vendor123',
    profileImage: null,
    createdAt: '2025-11-15',
  },
  {
    id: '2',
    name: 'Priya Sharma',
    email: 'priya@stylehaus.com',
    phone: '+91 87654 32109',
    businessName: 'Style Haus Boutique',
    businessCategory: 'Fashion & Apparel',
    city: 'Delhi',
    role: 'vendor',
    password: 'vendor123',
    profileImage: null,
    createdAt: '2025-12-01',
  },
  {
    id: '3',
    name: 'Admin User',
    email: 'admin@mediaflow.com',
    phone: '+91 99999 00000',
    businessName: 'MediaFlow Corp',
    businessCategory: 'Marketing',
    city: 'Bangalore',
    role: 'admin',
    password: 'admin123',
    profileImage: null,
    createdAt: '2025-01-01',
  },
];

export const mockCampaigns = [
  {
    id: 'c1',
    vendorId: '1',
    vendorName: 'Rajesh Kumar',
    businessName: 'Fresh Bites Restaurant',
    productName: 'Weekend Brunch Special',
    productDescription: 'Unlimited brunch buffet with 50+ items, live cooking stations, and craft cocktails. Perfect for family gatherings and weekend celebrations.',
    productCategory: 'Food & Dining',
    images: [],
    hasIdea: false,
    ideaDescription: '',
    targetAudience: 50000,
    budget: 25000,
    timeline: { start: '2026-01-15', end: '2026-02-15' },
    channels: ['Social Media', 'Google Ads', 'Influencer'],
    specialNotes: 'Focus on families and young professionals in South Mumbai',
    status: 'active',
    companyNotes: 'Great campaign potential. Targeting food bloggers in Mumbai area.',
    analytics: { reach: 42350, impressions: 128900, clicks: 3240, engagementRate: 4.8 },
    createdAt: '2026-01-10',
    updatedAt: '2026-02-01',
  },
  {
    id: 'c2',
    vendorId: '1',
    vendorName: 'Rajesh Kumar',
    businessName: 'Fresh Bites Restaurant',
    productName: 'Dine-In Loyalty Program',
    productDescription: 'Earn reward points on every dine-in order. Redeem for free meals, drinks, and exclusive chef-table experiences.',
    productCategory: 'Food & Dining',
    images: [],
    hasIdea: true,
    ideaDescription: 'A loyalty-card style campaign with QR codes that customers can scan',
    targetAudience: 30000,
    budget: 15000,
    timeline: { start: '2026-03-01', end: '2026-04-30' },
    channels: ['Social Media', 'Local Ads'],
    specialNotes: 'Need to design loyalty cards as well',
    status: 'pending',
    companyNotes: '',
    analytics: { reach: 0, impressions: 0, clicks: 0, engagementRate: 0 },
    createdAt: '2026-02-20',
    updatedAt: '2026-02-20',
  },
  {
    id: 'c3',
    vendorId: '2',
    vendorName: 'Priya Sharma',
    businessName: 'Style Haus Boutique',
    productName: 'Spring Collection 2026',
    productDescription: 'Handcrafted ethnic and fusion wear featuring sustainable fabrics. Designed for modern women who value tradition and style.',
    productCategory: 'Fashion',
    images: [],
    hasIdea: false,
    ideaDescription: '',
    targetAudience: 75000,
    budget: 45000,
    timeline: { start: '2026-02-01', end: '2026-03-31' },
    channels: ['Social Media', 'Influencer', 'Google Ads'],
    specialNotes: 'Need Instagram Reels and Pinterest campaigns targeting women 22-40',
    status: 'completed',
    companyNotes: 'Fantastic ROI. Campaign exceeded all targets. Recommend re-run for Fall.',
    analytics: { reach: 185200, impressions: 520000, clicks: 12800, engagementRate: 6.2 },
    createdAt: '2026-01-20',
    updatedAt: '2026-03-31',
  },
  {
    id: 'c4',
    vendorId: '2',
    vendorName: 'Priya Sharma',
    businessName: 'Style Haus Boutique',
    productName: 'Bridal Wear Pre-booking',
    productDescription: 'Exclusive bridal lehengas and sarees with custom fitting. Early booking discount campaign for the wedding season.',
    productCategory: 'Fashion',
    images: [],
    hasIdea: false,
    ideaDescription: '',
    targetAudience: 40000,
    budget: 35000,
    timeline: { start: '2026-04-01', end: '2026-05-31' },
    channels: ['Social Media', 'Google Ads'],
    specialNotes: 'Target brides-to-be and their families in North India',
    status: 'approved',
    companyNotes: 'Campaign approved. Will launch on April 1st with Instagram carousel ads.',
    analytics: { reach: 0, impressions: 0, clicks: 0, engagementRate: 0 },
    createdAt: '2026-03-01',
    updatedAt: '2026-03-05',
  },
];

export const businessCategories = [
  'Food & Beverage',
  'Fashion & Apparel',
  'Health & Wellness',
  'Beauty & Salon',
  'Education & Coaching',
  'Real Estate',
  'Retail & E-commerce',
  'Automotive',
  'Home Services',
  'Technology',
  'Sports & Fitness',
  'Travel & Tourism',
  'Entertainment',
  'Professional Services',
  'Other',
];

export const channelOptions = [
  'Social Media',
  'Google Ads',
  'Influencer',
  'Local Ads',
  'Content Marketing',
  'Email Marketing',
  'Video Marketing',
];
